language: java

arch:
- amd64
- arm64

jdk:
- openjdk11

cache:
  directories:
  - "$HOME/.m2"

addons:
  apt:
    packages:
    - maven
    - python3

env:
  global:
  - MVN="mvn -B -f druid/pom.xml"
  - MAVEN_SKIP="-Pskip-static-checks -Ddruid.console.skip=true -Dmaven.javadoc.skip=true"
  - MAVEN_SKIP_TESTS="-Pskip-tests"
  - DOCKER_REGISTRY=ghcr.io
  - DOCKER_REPOSITORY=apache/druid
  - secure: PmmRnWVJnR1wZ+9LOoyIhsTfpXBYpGLKSp6ZXsLFFdvWweEBC1cSIWcGvaXgOVPAWDsz3mugp8R2LhQz45vEkQc2KIuQZv9o3OPMcYQuAUUql8fYaQM1da23H2VTrdgKVONPDSz9XweH4KG0nYlRj/MgHAAPHJkmAR6RzWtTV0WhLZcDXujk67ENaPcFSMTIrDFkoWo2Hk8ccAgtYFz4jHlHdSazFZ2ArW/vwr9BAelBpTSPIrU/NGzQ1jcfji582mjLw0mTvDS8y6Nt+Be+3Dos5Fdy9tVtJb/3JC+2DabEVtVqEKZa0EJoYrKkDk7Co3JaCdeR9Qi9ly8ck8kMlqk0WD0vzrQCcZPcgZnX8/jTJhP4cS11Z8jpyQR2TcgCERZB6naix17GPfh9AbGxu01r2jlXhpjlEtBvUKw9w05h314fwyHEbNp8lY9sRLtaVBpyIC3PAYe5rVRbTJwMZwO9td46C0bbyrKjWihBxleg+yiwJZGMUXWUhWPbQ4r/basqddH+yhCK44uX1nw30NIrdmOk5S+0HAl9SvZanRdBjUngezxJDbFomUWN3LyJfZOURMerckFDFI2KlweDPS7NRmZEYb2Z6VTcGeKMNw1nxyMzNWuCU36i/zBsMJVmYg/UT2t6qsQit/70YGeuiE2Hn3NxaFq/mZOWtXeRdVw=
  - secure: Ls+IOOCgBJTaqWdx1iLNwxfp5ZiUBmpiqZVJHm8j+hSoujVXxHCgFSP4Z+JJNy/Le65or14BexNyjk+A7fg4emlutONtsKrwhnA5kei3WSKzdHZE17hK5u6jwcgE6HOj2Yccdo3+czWU2dxgVb9O/UiqdpGokRS1MVz2lAwiIfYxbG1xdLYvIRvQa59W6pC8F+GTJxAkSF5p2CknziLifN0GVKqK0OCR9OM3BlvXe/FPDIMRsgmFF+4o6kwCfn8xqaq0uKBWf5bIDC81WX4+8fOXY9Z/f7CqiPPwKEwcdM9TqQOtjdoHUGueZEYEDRm99NLS2A8TWTBXJEHN8wdoQpy/kIwCAGZShU74EWaRE84HdfWJkJJIug6h6yFPy/EPQN2Wyo65h1sFNzy/8ykRnWCzYeqryhuCLD3SzZ4g2yawS1EPFY959lBwjiTUqsb3Mb42FEdtawXkbcGXsjMkaPzHcRZJmuWHo/iRHLXgC/XGUhnZDOgd3IFNO8HFgPWBgRvGAAr61WdsccUf2EzQ1JuPhRglvm+u5r2xWaJ6e4+mpXiJsA603Qh1RKR6GZwhaBXZ5jiQ2STjMYauE+CsIDg+OC0Zj4T1vjUnkBLvaTfxZLj5x5yMzRv7ixWvM/fcaH516rGWDLms20Ja76yQZM6pYe0bTG3Nqtmi/E4ODJI=

services:
- docker

stages:
- build
- manifest

before_script:
- export DRUID_RELEASE=$(curl -s https://api.github.com/repos/apache/druid/releases/latest | jq .tag_name -r)
- git -C druid checkout $DRUID_RELEASE 
- export DRUID_VERSION=$(${MVN} -q org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -DforceStdout=true)
- export IMAGE_NAME=${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${DOCKER_REPOSITORY}
- export IMAGE_TAG=${DRUID_VERSION}-${TRAVIS_CPU_ARCH}
- export DRUID_IMAGE=${IMAGE_NAME}:${IMAGE_TAG}

script:
- echo $DRUID_VERSION
- "${MVN} install -Pdist,bundle-contrib-exts ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS}"
- docker build --build-arg DRUID_VERSION=${DRUID_VERSION} -t ${DRUID_IMAGE} .
- &docker-login echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
  ${DOCKER_REGISTRY}

deploy:
  provider: script
  on:
    all_branches: true
  script: docker push ${DRUID_IMAGE}

jobs:
  include:
  - stage: manifest
    install: skip
    script: skip
    after_deploy:
    - *docker-login
    - docker manifest create ${IMAGE_NAME}:${DRUID_VERSION} ${IMAGE_NAME}:${DRUID_VERSION}-amd64 ${IMAGE_NAME}:${DRUID_VERSION}-arm64;
      docker manifest annotate ${IMAGE_NAME}:${DRUID_VERSION}-amd64 --os linux --arch amd64;
      docker manifest annotate ${IMAGE_NAME}:${DRUID_VERSION}-arm64 --os linux --arch arm64 --variant v8;
    - docker manifesh push ${IMAGE_NAME}:${DRUID_VERSION}
