language: java

arch:
  - arm64

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

addons:
  apt:
    packages:
      - maven
      - python3

env:
  global:
    - MVN="mvn -B -f druid/pom.xml"
    - > # Various options to make execution of maven goals faster (e.g., mvn install)
      MAVEN_SKIP="-Pskip-static-checks -Ddruid.console.skip=true -Dmaven.javadoc.skip=true"
    - MAVEN_SKIP_TESTS="-Pskip-tests"

services:
  - docker

jobs:
  include:
    - name: "build druid image"
      before_script:
      - export DRUID_VERSION=$(${MVN} -q org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -DforceStdout=true)
      script:
      - echo $DRUID_VERSION
      - ${MVN} install -Pdist,bundle-contrib-exts ${MAVEN_SKIP} ${MAVEN_SKIP_TESTS}
      - docker build --build-arg DRUID_VERSION=${DRUID_VERSION} -t apache/druid:${DRUID_VERSION} .
