name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: ARM runner
      uses: pguyot/arm-runner-action@v2.3.0
    - name: Build the Docker image
      run: docker build . --file distribution/docker/Dockerfile --tag arm64/apache/druid:$(date +%s)
